site_name: Ning Xin

# 设计主题
theme:
  name: material
  palette: 
      primary: "light blue"
      accent: "blue"
  font:
      text: Roboto
      code: Roboto Mono
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
